sudo: required
services:
  - docker

before_install:
  - docker build -t ldkhang/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ldkhang/client-test npm test -- --coverage

after_success
  - docker build -t ldkhang/client-prod ./client
  - docker build -t ldkhang/nginx-prod ./nginx
  - docker build -t ldkhang/server-prod ./server
  - docker build -t ldkhang/worker-prod ./worker
